server:
  port: 8090

spring:
  application:
    name: spring-cloud-test-provider-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.10/ds?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect